### PR TITLE
Fixes fee errors

### PR DESCRIPTION
**Pull request by chillalittle**
Hi flufy,

Please review. Unsure about the CET_AS_FEE Feature

### CODE REVIEW

**Comment by flufy3d** [comment]
VIP_membership is good why you delete it?

**Comment by flufy3d** [comment]
oh, I see
you use maker_fee_rate from response.
so it's no need to compute by itself , right?

**Comment by chillalittle** [comment]
Thing is it mined a lot more then my difficulty per Hour on Coinex is. That was the fix yesterday which then was the right number as on the Account's mining page. it broke the difficulty vs. prediction numbers. the fees are in the Order-API and already adjusted by VIP.  Can you please check if this is the case for CET_AS_FEE 50% too ?

**Comment by flufy3d** [comment]
yes ,it's should be work too,I have asked the CTO from Coinex

**Comment by flufy3d** [comment]
see my commit
https://github.com/flufy3d/CoinexMiner/commit/53834df2d4d87afb73507ae22b1a44d72873ac16

it's no need doing CET_AS_FEE 50%  too

**Pull request merged**
